### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by FObersteiner** [leroycep/zig-tzif#3]
Hi there @leroycep , I recently found your repo while looking how datetime (and time zone) handling is (or could be) implemented in Zig.

The last update to this repo was quiet some time ago, the language has evolved a bit since then and there's currently a TZif reader in the zig std lib. However, what I found to be missing there is a parser for the POSIX rule, found in the TZif v2+ footer. Since I found this kind of tricky, I was very happy to find your code :)

Do you have any plans with this repo?

**Comment by leroycep** [comment]
It is not active at the moment, I wouldn't mind updating it or adding a small feature or two though.

**Comment by leroycep** [comment]
I've gone ahead and updated it to work with version 0.11.0 of Zig, feel free to try it out. I haven't tried out the standard library TZif parser, so I can't offer any comparison at the moment.

I also have a partial port of the rust chrono library done, but I'm not sure it translates super well from rust. There have been other people working on datetime handling in Zig, but again I haven't really used them myself.

**Comment by FObersteiner** [comment]
> I've gone ahead and updated it to work with version 0.11.0 of Zig, feel free to try it out. I haven't tried out the standard library TZif parser, so I can't offer any comparison at the moment.

Thanks a lot, I will sure give it a try :)

Regarding the TZif parser in the standard library, I'm not sure I understand why it's in the standard lib in the first place 👾 Anyhow, I played around with it, works quite well. But it doesn't handle the footer of the v2+ files, which is important I think since AFAIK, current TZif files do not make use of the 64 bit range. Transition times span basically the same range as the v1 files. Although that *could* of course be extended in the future. And of course for many time zones, there simply are no transition times (no DST), so you have to use the posix rule if I didn't miss anything.

**Comment by FObersteiner** [comment]
@leroycep did you consider contributing the POSIX TZ parser to the Zig standard library? 
I mean, there's a TZif parser in https://github.com/ziglang/zig/blob/master/lib/std/tz.zig, but it only extracts the footer, it doesn't parse it. That makes it incomplete and partly useless in my eyes - many time zones rely on that rule, not only in the far future. I haven't been observing the Zig ecosystem for long, so not sure if the core team *removes* stuff from std, i.e. if there's a chance they will remove `tz`. Probably depends on which part of Zig is using it (I have not investigated). Anyways, adding POSIX TZ parser to `std.tz` might be worth at least a try, after all the work you put into it?

**Comment by leroycep** [comment]
I hadn't considered it before, but I'm not opposed. I think when I initially wrote this I assumed that Zig was going in the same direction as Rust with std/third-party libraries, but if there's a TZif parser in the standard library, I see no reason it shouldn't support Posix TZ as well.

**Comment by leroycep** [comment]
Following up on #9, I've gone ahead and revived the `chrono-zig` project: https://codeberg.org/geemili/chrono-zig

I've copied the changes we recently made in this repository into the `chrono-zig` repo, and I've implemented [the algorithms described by Howard Hinnant](https://howardhinnant.github.io/date_algorithms.html). There's an example that prints out the local date and time.

**Comment by FObersteiner** [comment]
Nice, thanks for letting me know. And you moved it to codeberg :)

**Comment by FObersteiner** [comment]
Hi there @leroycep, I saw your reaction to my post over on ziggit.dev, and that brought me back here... For zdt, I still have the long-term goal to have a POSIX TZ string parser and rule implementation. If I would write that, that would probably be heavily inspired by your work here, so I was wondering if you'd be interested in contributing to zdt?
